const isoCodes = {
  None: "None",
  au: "Australia",
  br: "Brazil",
  ca: "Canada",
  cn: "China",
  eg: "Egypt",
  fr: "France",
  de: "Germany",
  gr: "Greece",
  hk: "Hong Kong",
  ie: "Ireland",
  il: "Israel",
  it: "Italy",
  in: "India",
  id: "Indonesia",
  jp: "Japan",
  kr: "Korea",
  my: "Malaysia",
  mx: "Mexico",
  pl: "Poland",
  nl: "Netherlands",
  nz: "New Zealand",
  ng: "Nigeria",
  no: "Norway",
  ru: "Russia",
  sa: "Saudi Arabia",
  sg: "Singapore",
  za: "South Africa",
  ch: "Switzerland",
  tw: "Taiwan",
  th: "Thailand",
  tr: "Turkey",
  ua: "Ukraine",
  gb: "United Kingdom",
  us: "United States",
  ae: "United Arab Emirates",
  ve: "Venezuela"
};

module.exports.isoCodes = isoCodes;
